import type { Vehicle, Driver, Delivery, Address, GeoPoint, FleetSummary } from "@fleetwise/shared";
import { DeliveryStatus } from "@fleetwise/shared";

// ─── Helpers ───────────────────────────────────────────
function uid(prefix: string, n: number): string {
  return `${prefix}-${String(n).padStart(3, "0")}`;
}

function iso(daysOffset: number): string {
  const d = new Date();
  d.setDate(d.getDate() + daysOffset);
  return d.toISOString();
}

const MIA: GeoPoint = { latitude: 25.7617, longitude: -80.1918 };
const ORL: GeoPoint = { latitude: 28.5383, longitude: -81.3792 };
const TPA: GeoPoint = { latitude: 27.9506, longitude: -82.4572 };
const JAX: GeoPoint = { latitude: 30.3322, longitude: -81.6557 };
const FTL: GeoPoint = { latitude: 26.1224, longitude: -80.1373 };
const TAL: GeoPoint = { latitude: 30.4383, longitude: -84.2807 };
const WPB: GeoPoint = { latitude: 26.7153, longitude: -80.0534 };
const NAP: GeoPoint = { latitude: 26.1420, longitude: -81.7948 };
const STPETE: GeoPoint = { latitude: 27.7676, longitude: -82.6403 };
const DAYTONA: GeoPoint = { latitude: 29.2108, longitude: -81.0228 };

function randomNear(base: GeoPoint, spreadKm: number): GeoPoint {
  // ~0.009 degrees ≈ 1 km
  const degPerKm = 0.009;
  return {
    latitude: base.latitude + (Math.random() - 0.5) * spreadKm * degPerKm * 2,
    longitude: base.longitude + (Math.random() - 0.5) * spreadKm * degPerKm * 2,
  };
}

// ─── Vehicles ──────────────────────────────────────────
export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: uid("V", 1),
    fleetId: "fleet-001",
    name: "Van Alpha",
    make: "Ford",
    model: "Transit 250",
    year: 2023,
    licensePlate: "7ABC123",
    vin: "1FTBR1C84PKA12345",
    status: "active",
    currentLocation: randomNear(MIA, 3),
    odometerKm: 15230,
    fuelType: "regular",
    fuelCapacityL: 95,
    assignedDriverId: uid("D", 1),
    category: "van",
    insuranceExpiry: iso(180),
    registrationExpiry: iso(300),
    createdAt: iso(-120),
    updatedAt: iso(-1),
  },
  {
    id: uid("V", 2),
    fleetId: "fleet-001",
    name: "Van Beta",
    make: "Mercedes",
    model: "Sprinter",
    year: 2024,
    licensePlate: "7XYZ456",
    vin: "WD3PE8CC0KJ67890",
    status: "active",
    currentLocation: randomNear(ORL, 5),
    odometerKm: 8450,
    fuelType: "diesel",
    fuelCapacityL: 75,
    assignedDriverId: uid("D", 2),
    category: "van",
    insuranceExpiry: iso(200),
    registrationExpiry: iso(365),
    createdAt: iso(-90),
    updatedAt: iso(-1),
  },
  {
    id: uid("V", 3),
    fleetId: "fleet-001",
    name: "Truck Delta",
    make: "Isuzu",
    model: "NPR-HD",
    year: 2022,
    licensePlate: "8LMN789",
    vin: "JALC4W168K7012345",
    status: "active",
    currentLocation: randomNear(TPA, 4),
    odometerKm: 28900,
    fuelType: "diesel",
    fuelCapacityL: 120,
    assignedDriverId: uid("D", 3),
    category: "truck",
    insuranceExpiry: iso(150),
    registrationExpiry: iso(250),
    createdAt: iso(-200),
    updatedAt: iso(-1),
  },
  {
    id: uid("V", 4),
    fleetId: "fleet-001",
    name: "Car Gamma",
    make: "Toyota",
    model: "Camry Hybrid",
    year: 2024,
    licensePlate: "6DEF345",
    vin: "4T1B11HK4JU123456",
    status: "idle",
    currentLocation: randomNear(JAX, 2),
    odometerKm: 3120,
    fuelType: "regular",
    fuelCapacityL: 50,
    assignedDriverId: uid("D", 4),
    category: "car",
    insuranceExpiry: iso(350),
    registrationExpiry: iso(400),
    createdAt: iso(-60),
    updatedAt: iso(-1),
  },
  {
    id: uid("V", 5),
    fleetId: "fleet-001",
    name: "Van Epsilon",
    make: "Ram",
    model: "ProMaster 2500",
    year: 2023,
    licensePlate: "9GHI012",
    vin: "3C6TRVDG2KE123456",
    status: "active",
    currentLocation: randomNear(FTL, 3),
    odometerKm: 19500,
    fuelType: "regular",
    fuelCapacityL: 90,
    assignedDriverId: uid("D", 5),
    category: "van",
    insuranceExpiry: iso(90),
    registrationExpiry: iso(180),
    createdAt: iso(-100),
    updatedAt: iso(-1),
  },
  {
    id: uid("V", 6),
    fleetId: "fleet-001",
    name: "Truck Zeta",
    make: "Hino",
    model: "268",
    year: 2024,
    licensePlate: "5JKL345",
    vin: "JHHSDM2H0MK123456",
    status: "active",
    currentLocation: randomNear(TAL, 5),
    odometerKm: 6700,
    fuelType: "diesel",
    fuelCapacityL: 140,
    assignedDriverId: uid("D", 6),
    category: "truck",
    insuranceExpiry: iso(270),
    registrationExpiry: iso(365),
    createdAt: iso(-80),
    updatedAt: iso(-1),
  },
  {
    id: uid("V", 7),
    fleetId: "fleet-001",
    name: "Van Eta",
    make: "Nissan",
    model: "NV2500",
    year: 2022,
    licensePlate: "4MNO678",
    vin: "1N6BF0LY0KN123456",
    status: "maintenance",
    currentLocation: randomNear(WPB, 1),
    odometerKm: 42100,
    fuelType: "regular",
    fuelCapacityL: 85,
    assignedDriverId: undefined,
    category: "van",
    insuranceExpiry: iso(30),
    registrationExpiry: iso(60),
    createdAt: iso(-300),
    updatedAt: iso(-1),
  },
  {
    id: uid("V", 8),
    fleetId: "fleet-001",
    name: "Car Theta",
    make: "Honda",
    model: "Civic",
    year: 2023,
    licensePlate: "3PQR901",
    vin: "19XFC2F89KE123456",
    status: "idle",
    currentLocation: randomNear(NAP, 2),
    odometerKm: 8900,
    fuelType: "regular",
    fuelCapacityL: 47,
    assignedDriverId: uid("D", 8),
    category: "car",
    insuranceExpiry: iso(200),
    registrationExpiry: iso(300),
    createdAt: iso(-50),
    updatedAt: iso(-1),
  },
  {
    id: uid("V", 9),
    fleetId: "fleet-001",
    name: "Truck Iota",
    make: "Ford",
    model: "F-650",
    year: 2023,
    licensePlate: "2STU234",
    vin: "1FDNF6DC7KD123456",
    status: "out_of_service",
    currentLocation: randomNear(STPETE, 1),
    odometerKm: 35000,
    fuelType: "diesel",
    fuelCapacityL: 200,
    assignedDriverId: undefined,
    category: "truck",
    insuranceExpiry: iso(100),
    registrationExpiry: iso(200),
    createdAt: iso(-150),
    updatedAt: iso(-1),
  },
  {
    id: uid("V", 10),
    fleetId: "fleet-001",
    name: "Van Kappa",
    make: "Ford",
    model: "E-350",
    year: 2024,
    licensePlate: "1VWX567",
    vin: "1FDSE35L0RH123456",
    status: "active",
    currentLocation: randomNear(DAYTONA, 3),
    odometerKm: 4500,
    fuelType: "regular",
    fuelCapacityL: 100,
    assignedDriverId: uid("D", 7),
    category: "van",
    insuranceExpiry: iso(300),
    registrationExpiry: iso(365),
    createdAt: iso(-30),
    updatedAt: iso(-1),
  },
];

// ─── Drivers ───────────────────────────────────────────
export const MOCK_DRIVERS: Driver[] = [
  {
    id: uid("D", 1),
    fleetId: "fleet-001",
    userId: "user-001",
    licenseNumber: "DL-FL-1234567",
    licenseExpiry: iso(500),
    assignedVehicleId: uid("V", 1),
    status: "on_delivery",
    rating: 4.8,
    totalDeliveries: 1240,
    phoneNumber: "+1-415-555-0101",
    createdAt: iso(-300),
    updatedAt: iso(-1),
  },
  {
    id: uid("D", 2),
    fleetId: "fleet-001",
    userId: "user-002",
    licenseNumber: "DL-FL-2345678",
    licenseExpiry: iso(400),
    assignedVehicleId: uid("V", 2),
    status: "on_delivery",
    rating: 4.5,
    totalDeliveries: 890,
    phoneNumber: "+1-310-555-0102",
    createdAt: iso(-200),
    updatedAt: iso(-1),
  },
  {
    id: uid("D", 3),
    fleetId: "fleet-001",
    userId: "user-003",
    licenseNumber: "DL-FL-3456789",
    licenseExpiry: iso(600),
    assignedVehicleId: uid("V", 3),
    status: "available",
    rating: 4.9,
    totalDeliveries: 2100,
    phoneNumber: "+1-619-555-0103",
    createdAt: iso(-500),
    updatedAt: iso(-1),
  },
  {
    id: uid("D", 4),
    fleetId: "fleet-001",
    userId: "user-004",
    licenseNumber: "DL-FL-4567890",
    licenseExpiry: iso(300),
    assignedVehicleId: uid("V", 4),
    status: "available",
    rating: 4.2,
    totalDeliveries: 430,
    phoneNumber: "+1-408-555-0104",
    createdAt: iso(-150),
    updatedAt: iso(-1),
  },
  {
    id: uid("D", 5),
    fleetId: "fleet-001",
    userId: "user-005",
    licenseNumber: "DL-FL-5678901",
    licenseExpiry: iso(200),
    assignedVehicleId: uid("V", 5),
    status: "on_delivery",
    rating: 4.7,
    totalDeliveries: 1560,
    phoneNumber: "+1-510-555-0105",
    createdAt: iso(-250),
    updatedAt: iso(-1),
  },
  {
    id: uid("D", 6),
    fleetId: "fleet-001",
    userId: "user-006",
    licenseNumber: "DL-FL-6789012",
    licenseExpiry: iso(450),
    assignedVehicleId: uid("V", 6),
    status: "on_delivery",
    rating: 3.9,
    totalDeliveries: 320,
    phoneNumber: "+1-916-555-0106",
    createdAt: iso(-100),
    updatedAt: iso(-1),
  },
  {
    id: uid("D", 7),
    fleetId: "fleet-001",
    userId: "user-007",
    licenseNumber: "DL-FL-7890123",
    licenseExpiry: iso(350),
    assignedVehicleId: uid("V", 10),
    status: "available",
    rating: 4.6,
    totalDeliveries: 780,
    phoneNumber: "+1-650-555-0107",
    createdAt: iso(-180),
    updatedAt: iso(-1),
  },
  {
    id: uid("D", 8),
    fleetId: "fleet-001",
    userId: "user-008",
    licenseNumber: "DL-FL-8901234",
    licenseExpiry: iso(250),
    assignedVehicleId: uid("V", 8),
    status: "offline",
    rating: 4.3,
    totalDeliveries: 560,
    phoneNumber: "+1-415-555-0108",
    createdAt: iso(-120),
    updatedAt: iso(-1),
  },
];

// ─── Addresses ─────────────────────────────────────────
function addr(street: string, city: string, coords: GeoPoint): Address {
  return {
    street,
    city,
    state: "FL",
    zipCode: String(90000 + Math.floor(Math.random() * 10000)),
    country: "US",
    coordinates: coords,
  };
}

// ─── Deliveries ────────────────────────────────────────
export const MOCK_DELIVERIES: Delivery[] = [
  {
    id: uid("DLV", 1),
    fleetId: "fleet-001",
    driverId: uid("D", 1),
    vehicleId: uid("V", 1),
    status: DeliveryStatus.InTransit,
    pickupAddress: addr("123 Market St", "Miami", MIA),
    dropoffAddress: addr("456 Mission St", "Miami", randomNear(MIA, 2)),
    scheduledPickupTime: iso(-1),
    scheduledDropoffTime: iso(0),
    packageDescription: "Office supplies (3 boxes)",
    packageWeightKg: 12.5,
    priority: "normal",
    customerName: "Acme Corp",
    customerPhone: "+1-415-555-1001",
    signatureRequired: false,
    paymentCollected: 0,
    distanceKm: 2.3,
    estimatedDurationMin: 15,
    createdAt: iso(-2),
    updatedAt: iso(-1),
  },
  {
    id: uid("DLV", 2),
    fleetId: "fleet-001",
    driverId: uid("D", 2),
    vehicleId: uid("V", 2),
    status: DeliveryStatus.PickedUp,
    pickupAddress: addr("789 Sunset Blvd", "Orlando", ORL),
    dropoffAddress: addr("1010 Wilshire Blvd", "Orlando", randomNear(ORL, 8)),
    scheduledPickupTime: iso(0),
    scheduledDropoffTime: iso(0),
    packageDescription: "Electronics (fragile)",
    packageWeightKg: 8.2,
    specialInstructions: "Ring doorbell twice",
    priority: "high",
    customerName: "TechGear Inc",
    customerPhone: "+1-310-555-1002",
    signatureRequired: true,
    paymentCollected: 25000,
    distanceKm: 8.7,
    estimatedDurationMin: 25,
    createdAt: iso(-2),
    updatedAt: iso(-1),
  },
  {
    id: uid("DLV", 3),
    fleetId: "fleet-001",
    driverId: uid("D", 3),
    vehicleId: uid("V", 3),
    status: DeliveryStatus.Assigned,
    pickupAddress: addr("321 Harbor Dr", "Tampa", TPA),
    dropoffAddress: addr("654 Ocean Ave", "Tampa", randomNear(TPA, 5)),
    scheduledPickupTime: iso(0),
    scheduledDropoffTime: iso(1),
    packageDescription: "Restaurant supplies (pallet)",
    packageWeightKg: 350,
    priority: "normal",
    customerName: "Coastal Eats",
    customerPhone: "+1-619-555-1003",
    signatureRequired: false,
    paymentCollected: 0,
    distanceKm: 5.1,
    estimatedDurationMin: 20,
    createdAt: iso(-1),
    updatedAt: iso(-1),
  },
  {
    id: uid("DLV", 4),
    fleetId: "fleet-001",
    driverId: uid("D", 5),
    vehicleId: uid("V", 5),
    status: DeliveryStatus.Delivered,
    pickupAddress: addr("147 Broadway", "Fort Lauderdale", FTL),
    dropoffAddress: addr("258 Telegraph Ave", "Fort Lauderdale", randomNear(FTL, 1.5)),
    scheduledPickupTime: iso(-2),
    scheduledDropoffTime: iso(-1),
    actualPickupTime: iso(-2),
    actualDropoffTime: iso(-1),
    packageDescription: "Medical supplies (refrigerated)",
    packageWeightKg: 25,
    priority: "urgent",
    customerName: "Bay Health",
    customerPhone: "+1-510-555-1004",
    signatureRequired: true,
    paymentCollected: 0,
    distanceKm: 1.8,
    estimatedDurationMin: 10,
    createdAt: iso(-3),
    updatedAt: iso(-1),
  },
  {
    id: uid("DLV", 5),
    fleetId: "fleet-001",
    driverId: uid("D", 6),
    vehicleId: uid("V", 6),
    status: DeliveryStatus.InTransit,
    pickupAddress: addr("963 Capitol Mall", "Tallahassee", TAL),
    dropoffAddress: addr("741 K St", "Tallahassee", randomNear(TAL, 3)),
    scheduledPickupTime: iso(-1),
    scheduledDropoffTime: iso(0),
    packageDescription: "Furniture (assembly required)",
    packageWeightKg: 80,
    specialInstructions: "Use freight elevator",
    priority: "low",
    customerName: "Capital Interiors",
    customerPhone: "+1-916-555-1005",
    signatureRequired: false,
    paymentCollected: 45000,
    distanceKm: 3.5,
    estimatedDurationMin: 20,
    createdAt: iso(-2),
    updatedAt: iso(-1),
  },
  {
    id: uid("DLV", 6),
    fleetId: "fleet-001",
    driverId: uid("D", 1),
    vehicleId: uid("V", 1),
    status: DeliveryStatus.Pending,
    pickupAddress: addr("55 2nd St", "Miami", MIA),
    dropoffAddress: addr("88 Howard St", "Miami", randomNear(MIA, 2)),
    scheduledPickupTime: iso(1),
    scheduledDropoffTime: iso(1),
    packageDescription: "Documents (envelope)",
    packageWeightKg: 0.5,
    priority: "high",
    customerName: "LegalEase LLP",
    customerPhone: "+1-415-555-1006",
    signatureRequired: true,
    paymentCollected: 0,
    distanceKm: 1.2,
    estimatedDurationMin: 8,
    createdAt: iso(0),
    updatedAt: iso(0),
  },
  {
    id: uid("DLV", 7),
    fleetId: "fleet-001",
    driverId: uid("D", 2),
    vehicleId: uid("V", 2),
    status: DeliveryStatus.Failed,
    pickupAddress: addr("333 Vine St", "Orlando", ORL),
    dropoffAddress: addr("444 Melrose Ave", "Orlando", randomNear(ORL, 6)),
    scheduledPickupTime: iso(-2),
    scheduledDropoffTime: iso(-1),
    packageDescription: "Perishable food items",
    packageWeightKg: 15,
    specialInstructions: "Customer not available — rescheduled",
    priority: "urgent",
    customerName: "FreshDirect",
    customerPhone: "+1-310-555-1007",
    signatureRequired: false,
    paymentCollected: 0,
    distanceKm: 6.3,
    estimatedDurationMin: 22,
    createdAt: iso(-3),
    updatedAt: iso(-1),
  },
  {
    id: uid("DLV", 8),
    fleetId: "fleet-001",
    driverId: uid("D", 7),
    vehicleId: uid("V", 10),
    status: DeliveryStatus.InTransit,
    pickupAddress: addr("1 Airport Blvd", "South Miami", DAYTONA),
    dropoffAddress: addr("200 Skyline Dr", "Daly City", randomNear(DAYTONA, 4)),
    scheduledPickupTime: iso(0),
    scheduledDropoffTime: iso(0),
    packageDescription: "Aviation parts",
    packageWeightKg: 45,
    priority: "high",
    customerName: "SkyTech Aviation",
    customerPhone: "+1-650-555-1008",
    signatureRequired: true,
    paymentCollected: 120000,
    distanceKm: 4.8,
    estimatedDurationMin: 18,
    createdAt: iso(-1),
    updatedAt: iso(-1),
  },
];

// ─── Fleet Summary ─────────────────────────────────────
export function getMockFleetSummary(): FleetSummary {
  return {
    totalVehicles: MOCK_VEHICLES.length,
    activeDrivers: MOCK_DRIVERS.filter((d) => d.status !== "offline").length,
    deliveriesToday: MOCK_DELIVERIES.filter((d) =>
      [DeliveryStatus.InTransit, DeliveryStatus.PickedUp, DeliveryStatus.Delivered].includes(d.status)
    ).length,
    fleetUtilizationPercent: Math.round(
      (MOCK_VEHICLES.filter((v) => v.status === "active").length / MOCK_VEHICLES.length) * 100
    ),
    totalDistanceKm: 1240,
    fuelCostTotal: 38450,
    maintenanceAlerts: MOCK_VEHICLES.filter((v) => v.status === "maintenance" || v.status === "out_of_service").length,
  };
}

// ─── GPS Simulation ────────────────────────────────────
export function simulateGpsUpdates(vehicles: Vehicle[]): Vehicle[] {
  return vehicles.map((v) => {
    if (v.status !== "active" || !v.currentLocation) return v;
    return {
      ...v,
      currentLocation: {
        latitude: v.currentLocation.latitude + (Math.random() - 0.5) * 0.002,
        longitude: v.currentLocation.longitude + (Math.random() - 0.5) * 0.003,
      },
      updatedAt: new Date().toISOString(),
    };
  });
}

// ─── Driver display helpers ────────────────────────────
// Extended info that combines Driver with a name field not in the shared type
export interface DriverDisplay extends Driver {
  name: string;
  email: string;
}

export const DRIVER_NAMES: Record<string, { name: string; email: string }> = {
  [uid("D", 1)]: { name: "Sarah Chen", email: "sarah.chen@fleetwise.com" },
  [uid("D", 2)]: { name: "Marcus Johnson", email: "marcus.j@fleetwise.com" },
  [uid("D", 3)]: { name: "Javier Rodriguez", email: "javier.r@fleetwise.com" },
  [uid("D", 4)]: { name: "Emily Park", email: "emily.park@fleetwise.com" },
  [uid("D", 5)]: { name: "David Kim", email: "david.kim@fleetwise.com" },
  [uid("D", 6)]: { name: "Lisa Thompson", email: "lisa.t@fleetwise.com" },
  [uid("D", 7)]: { name: "Robert Nguyen", email: "robert.n@fleetwise.com" },
  [uid("D", 8)]: { name: "Angela Martinez", email: "angela.m@fleetwise.com" },
};

export function getDriverDisplay(driver: Driver): DriverDisplay {
  if (driver.name && driver.email) {
    return { ...driver, name: driver.name, email: driver.email };
  }
  const info = DRIVER_NAMES[driver.id] ?? { name: "Unknown", email: "unknown@fleetwise.com" };
  return { ...driver, ...info };
}

export function getDriverDisplayById(id: string): DriverDisplay | undefined {
  const d = MOCK_DRIVERS.find((dr) => dr.id === id);
  if (!d) return undefined;
  return getDriverDisplay(d);
}

export function getVehicleDriverName(vehicle: Vehicle): string {
  if (!vehicle.assignedDriverId) return "—";
  return DRIVER_NAMES[vehicle.assignedDriverId]?.name ?? "Unknown";
}
